### ISSUE TITLE
Spec doesn't time out

### ISSUE THREAD

**Issue by asbjornu** [laserlemon/rspec-wait#30] opened 2020-12-08 17:42 UTC
I have an RSpec test set up as follows:

```ruby
require 'rspec/wait'

describe Commander do
  let(:logger) { SpecLogger.new(:info) }

  subject do
    commander = Commander.new
    commander.logger = logger
    commander
  end

  describe '#execute', wait: { timeout: 10 } do
    before { subject.execute(['serve']) }

    it {
      wait_for(logger.message).to include('Serving')
    }
  end
end
```

When executing this spec, it just hangs on the `before { subject.execute(['serve']) }` line. I would expect the spec to fail (time out) after 10 seconds. Ideas?

**Comment by laserlemon** [comment] 2024-04-24 13:04
Without knowing more about `SpecLogger` or `Commander`, I can't reproduce the issue. Closing for now, but if you can still reproduce the issue on the `v1` branch (understanding that v1 will no longer time out in the middle of a block call), please feel free to reopen with full reproduction steps!

**Closed by laserlemon** 2024-04-24 13:04 UTC
